name: Build and Test on Multiple Platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build zig
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - name: Build with zig for aarch64-linux 
        working-directory: ./zig
        run: zig build -Dtarget=aarch64-linux
      - name: Upload artifact for aarch64-linux
        uses: actions/upload-artifact@v4
        with:
          name: cq-aarch64-linux
          path: ./zig/zig-out/.linux-.aarch64
      - name: Build with zig for x86_64-linux 
        working-directory: ./zig
        run: zig build -Dtarget=x86_64-linux
      - name: Upload artifact for x86_64-linux
        uses: actions/upload-artifact@v4
        with:
          name: cq-aarch64-linux
          path: ./zig/zig-out/.linux-.aarch64
      - name: Build with zig for x86_64-windows 
        working-directory: ./zig
        run: zig build -Dtarget=x86_64-windows 
      - name: Upload artifact for x86_64-windows
        uses: actions/upload-artifact@v4
        with:
          name: cq-x86_64-windows
          path: ./zig/zig-out/.x86_64-.windows

      - name: Build with zig for aarch64-macos 
        working-directory: ./zig
        run: zig build -Dtarget=aarch64-macos
      - name: Upload artifact for aarch64-macos
        uses: actions/upload-artifact@v4
        with:
          name: cq-aarch64-macos
          path: ./zig/zig-out/.aarch64-.macos
      - name: Build with zig for x86_64-macos
        working-directory: ./zig
        run: zig build -Dtarget=x86_64-macos
      - name: Upload artifact for x86_64-macos
        uses: actions/upload-artifact@v4
        with:
          name: cq-aarch64-linux
          path: ./zig/zig-out/.x86_64-.macos
